### ISSUE TITLE
Respec with pet class duping pet on main char

### ISSUE THREAD

**Issue by morlock76** [Deevian/pathfinder-kingmaker-respec#14]
Greeting, love your work.
Since the update yesterday while resetting the main char with a pet adds a new pet.
Before that I had some left over pets in the world from chars that used to have the feat / ability and now don't (or were deleted), now it just adds a pet.
Tried to look into party.json and it seems there is no deletion of pets in any way. Even the deleted companions (mercs) left their pets in the party.json.
Wondering how the loosing of druid powers due to alignment change would be handled, can't figure out a way to test it quickly though.
Hope this helps :-)

**Comment by Deevian** [comment]
Regarding the pet dupe -- have you tried also respeccing the unknowns? Would that remove the pets? I assume so, since that's what happened before. Might have to look into if the characters have a master, and have to force a respec if the master is respecced.

Regarding spell loss after alignment change -- that's baked into the game. I mean, you can whether you want to keep your old alignment in the game in step 7, but other than that, casting spells outside of your alignment will always be a no-go.

**Comment by morlock76** [comment]
Tried respeccing the unknowns. It did not remove the pet (of my main), but the old pet is not under control any more, so (for me, for now) perfect :-)
The alignment change was an idea of a workaround / cleanup, not needed any more.
