### ISSUE TITLE
Alignment Change Issue

### ISSUE THREAD

**Issue by mirkomina** [Deevian/pathfinder-kingmaker-respec#15]
Hi 
I would like to point out this issue.
During the respect is impossible to change the alignment of the main character and respect in class that have special requirements, here my case:

Chaotic Good Ranger to respect in Lawful Good Monk.
During the step 7, I can set the new alignment during the character creation at level 1 and select the monk class.
When I do the final steps 10 and 11, the character returns to the original level (8) but also the alignment return to old value of Chaotic Good.

I hope it helps.
Regards,
Mirko

**Comment by Deevian** [comment]
That seems... odd. Like, respec-didn't-go-through odd.

Alignment is kept if you level up right after the first save. If you don't want to keep the alignment, just do the entire process, then level up afterwards.

Returning to the original level is just almost impossible, since I'm not messing around with that. Are you selecting the correct saves?

**Comment by mirkomina** [comment]
It worked. 
I think it was a problem on my side at wifi connection, during the second upload the pc switched wifi. Maybe the service loses some data during the refresh of the page or similar.

Many Thanks
